//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gaic.insuredPortal.Provider.WcfServices.BcPortalService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class PolicyNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string accountNameField;
        
        private string accountStatusField;
        
        private string sendInvoicesByField;
        
        private decimal accountBalanceField;
        
        private decimal amountDueField;
        
        private System.Nullable<decimal> lastPaymentAmountField;
        
        private System.Nullable<System.DateTime> lastPaymentDateField;
        
        private System.Nullable<System.DateTime> lastInvoiceDateField;
        
        private System.Nullable<System.DateTime> invoiceDueDateField;
        
        private string paymentPlanField;
        
        private string sendProducerOutputByField;
        
        private BillingTransaction[] billingTransactionsField;
        
        private Payment[] scheduledPaymentsField;
        
        private BillingDocument[] billingDocumentsField;
        
        private Policy[] policiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
                this.RaisePropertyChanged("AccountStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SendInvoicesBy {
            get {
                return this.sendInvoicesByField;
            }
            set {
                this.sendInvoicesByField = value;
                this.RaisePropertyChanged("SendInvoicesBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal AccountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
                this.RaisePropertyChanged("AccountBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal AmountDue {
            get {
                return this.amountDueField;
            }
            set {
                this.amountDueField = value;
                this.RaisePropertyChanged("AmountDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> LastPaymentAmount {
            get {
                return this.lastPaymentAmountField;
            }
            set {
                this.lastPaymentAmountField = value;
                this.RaisePropertyChanged("LastPaymentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> LastPaymentDate {
            get {
                return this.lastPaymentDateField;
            }
            set {
                this.lastPaymentDateField = value;
                this.RaisePropertyChanged("LastPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> LastInvoiceDate {
            get {
                return this.lastInvoiceDateField;
            }
            set {
                this.lastInvoiceDateField = value;
                this.RaisePropertyChanged("LastInvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> InvoiceDueDate {
            get {
                return this.invoiceDueDateField;
            }
            set {
                this.invoiceDueDateField = value;
                this.RaisePropertyChanged("InvoiceDueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaymentPlan {
            get {
                return this.paymentPlanField;
            }
            set {
                this.paymentPlanField = value;
                this.RaisePropertyChanged("PaymentPlan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SendProducerOutputBy {
            get {
                return this.sendProducerOutputByField;
            }
            set {
                this.sendProducerOutputByField = value;
                this.RaisePropertyChanged("SendProducerOutputBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BillingTransaction[] BillingTransactions {
            get {
                return this.billingTransactionsField;
            }
            set {
                this.billingTransactionsField = value;
                this.RaisePropertyChanged("BillingTransactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ScheduledPayment", IsNullable=false)]
        public Payment[] ScheduledPayments {
            get {
                return this.scheduledPaymentsField;
            }
            set {
                this.scheduledPaymentsField = value;
                this.RaisePropertyChanged("ScheduledPayments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountBillingDocument", IsNullable=false)]
        public BillingDocument[] BillingDocuments {
            get {
                return this.billingDocumentsField;
            }
            set {
                this.billingDocumentsField = value;
                this.RaisePropertyChanged("BillingDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Policy[] Policies {
            get {
                return this.policiesField;
            }
            set {
                this.policiesField = value;
                this.RaisePropertyChanged("Policies");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class BillingTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime processDateField;
        
        private string transactionTypeField;
        
        private System.Nullable<decimal> amountField;
        
        private System.Nullable<decimal> netAmountField;
        
        private System.Nullable<decimal> commRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime ProcessDate {
            get {
                return this.processDateField;
            }
            set {
                this.processDateField = value;
                this.RaisePropertyChanged("ProcessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> NetAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
                this.RaisePropertyChanged("NetAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> CommRate {
            get {
                return this.commRateField;
            }
            set {
                this.commRateField = value;
                this.RaisePropertyChanged("CommRate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class Payment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dueDateField;
        
        private System.DateTime invoiceDateField;
        
        private System.Nullable<decimal> amountField;
        
        private System.Nullable<decimal> netAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("DueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> NetAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
                this.RaisePropertyChanged("NetAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class BillingDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime documentDateField;
        
        private string documentTypeField;
        
        private string documentUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
                this.RaisePropertyChanged("DocumentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string DocumentUID {
            get {
                return this.documentUIDField;
            }
            set {
                this.documentUIDField = value;
                this.RaisePropertyChanged("DocumentUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class Policy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyNumberField;
        
        private string policySymbolField;
        
        private string policyModuleField;
        
        private string policyVersionField;
        
        private string accountNumberField;
        
        private System.DateTime policyEffDateField;
        
        private System.DateTime policyExpiryDateField;
        
        private string policyBillingStatusField;
        
        private System.Nullable<decimal> policyTotalPremiumField;
        
        private System.Nullable<decimal> policyBalanceField;
        
        private System.Nullable<decimal> policyAmtPastDueField;
        
        private System.Nullable<decimal> policyAmtDueField;
        
        private System.Nullable<decimal> policyAmtCurrentDueField;
        
        private System.Nullable<decimal> policyTotalNetPremiumField;
        
        private System.Nullable<decimal> policyNetBalanceField;
        
        private System.Nullable<decimal> policyNetAmtPastDueField;
        
        private System.Nullable<decimal> policyNetAmtDueField;
        
        private System.Nullable<decimal> policyNetAmtCurrentDueField;
        
        private string policyStatusField;
        
        private string policyPaymentPlanField;
        
        private string policyBusinessUnitField;
        
        private string policyProducerCodeField;
        
        private System.Nullable<System.DateTime> policyNextDueDateField;
        
        private string policySendStatementByField;
        
        private string policyBillingRepEmailField;
        
        private BillingTransaction[] billingTransactionsField;
        
        private Payment[] scheduledPaymentsField;
        
        private BillingDocument[] billingDocumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PolicySymbol {
            get {
                return this.policySymbolField;
            }
            set {
                this.policySymbolField = value;
                this.RaisePropertyChanged("PolicySymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PolicyModule {
            get {
                return this.policyModuleField;
            }
            set {
                this.policyModuleField = value;
                this.RaisePropertyChanged("PolicyModule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string PolicyVersion {
            get {
                return this.policyVersionField;
            }
            set {
                this.policyVersionField = value;
                this.RaisePropertyChanged("PolicyVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime PolicyEffDate {
            get {
                return this.policyEffDateField;
            }
            set {
                this.policyEffDateField = value;
                this.RaisePropertyChanged("PolicyEffDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime PolicyExpiryDate {
            get {
                return this.policyExpiryDateField;
            }
            set {
                this.policyExpiryDateField = value;
                this.RaisePropertyChanged("PolicyExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PolicyBillingStatus {
            get {
                return this.policyBillingStatusField;
            }
            set {
                this.policyBillingStatusField = value;
                this.RaisePropertyChanged("PolicyBillingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> PolicyTotalPremium {
            get {
                return this.policyTotalPremiumField;
            }
            set {
                this.policyTotalPremiumField = value;
                this.RaisePropertyChanged("PolicyTotalPremium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> PolicyBalance {
            get {
                return this.policyBalanceField;
            }
            set {
                this.policyBalanceField = value;
                this.RaisePropertyChanged("PolicyBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> PolicyAmtPastDue {
            get {
                return this.policyAmtPastDueField;
            }
            set {
                this.policyAmtPastDueField = value;
                this.RaisePropertyChanged("PolicyAmtPastDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> PolicyAmtDue {
            get {
                return this.policyAmtDueField;
            }
            set {
                this.policyAmtDueField = value;
                this.RaisePropertyChanged("PolicyAmtDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> PolicyAmtCurrentDue {
            get {
                return this.policyAmtCurrentDueField;
            }
            set {
                this.policyAmtCurrentDueField = value;
                this.RaisePropertyChanged("PolicyAmtCurrentDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> PolicyTotalNetPremium {
            get {
                return this.policyTotalNetPremiumField;
            }
            set {
                this.policyTotalNetPremiumField = value;
                this.RaisePropertyChanged("PolicyTotalNetPremium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> PolicyNetBalance {
            get {
                return this.policyNetBalanceField;
            }
            set {
                this.policyNetBalanceField = value;
                this.RaisePropertyChanged("PolicyNetBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> PolicyNetAmtPastDue {
            get {
                return this.policyNetAmtPastDueField;
            }
            set {
                this.policyNetAmtPastDueField = value;
                this.RaisePropertyChanged("PolicyNetAmtPastDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<decimal> PolicyNetAmtDue {
            get {
                return this.policyNetAmtDueField;
            }
            set {
                this.policyNetAmtDueField = value;
                this.RaisePropertyChanged("PolicyNetAmtDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> PolicyNetAmtCurrentDue {
            get {
                return this.policyNetAmtCurrentDueField;
            }
            set {
                this.policyNetAmtCurrentDueField = value;
                this.RaisePropertyChanged("PolicyNetAmtCurrentDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string PolicyStatus {
            get {
                return this.policyStatusField;
            }
            set {
                this.policyStatusField = value;
                this.RaisePropertyChanged("PolicyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string PolicyPaymentPlan {
            get {
                return this.policyPaymentPlanField;
            }
            set {
                this.policyPaymentPlanField = value;
                this.RaisePropertyChanged("PolicyPaymentPlan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PolicyBusinessUnit {
            get {
                return this.policyBusinessUnitField;
            }
            set {
                this.policyBusinessUnitField = value;
                this.RaisePropertyChanged("PolicyBusinessUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string PolicyProducerCode {
            get {
                return this.policyProducerCodeField;
            }
            set {
                this.policyProducerCodeField = value;
                this.RaisePropertyChanged("PolicyProducerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=22)]
        public System.Nullable<System.DateTime> PolicyNextDueDate {
            get {
                return this.policyNextDueDateField;
            }
            set {
                this.policyNextDueDateField = value;
                this.RaisePropertyChanged("PolicyNextDueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string PolicySendStatementBy {
            get {
                return this.policySendStatementByField;
            }
            set {
                this.policySendStatementByField = value;
                this.RaisePropertyChanged("PolicySendStatementBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string PolicyBillingRepEmail {
            get {
                return this.policyBillingRepEmailField;
            }
            set {
                this.policyBillingRepEmailField = value;
                this.RaisePropertyChanged("PolicyBillingRepEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=25)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BillingTransaction[] BillingTransactions {
            get {
                return this.billingTransactionsField;
            }
            set {
                this.billingTransactionsField = value;
                this.RaisePropertyChanged("BillingTransactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=26)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ScheduledPayment", IsNullable=false)]
        public Payment[] ScheduledPayments {
            get {
                return this.scheduledPaymentsField;
            }
            set {
                this.scheduledPaymentsField = value;
                this.RaisePropertyChanged("ScheduledPayments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=27)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PolicyBillingDocument", IsNullable=false)]
        public BillingDocument[] BillingDocuments {
            get {
                return this.billingDocumentsField;
            }
            set {
                this.billingDocumentsField = value;
                this.RaisePropertyChanged("BillingDocuments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class PolicyStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyKeyStringField;
        
        private string policyStatusField;
        
        private string policyBillingTypeField;
        
        private int policyDelinquencyCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PolicyKeyString {
            get {
                return this.policyKeyStringField;
            }
            set {
                this.policyKeyStringField = value;
                this.RaisePropertyChanged("PolicyKeyString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PolicyStatus {
            get {
                return this.policyStatusField;
            }
            set {
                this.policyStatusField = value;
                this.RaisePropertyChanged("PolicyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PolicyBillingType {
            get {
                return this.policyBillingTypeField;
            }
            set {
                this.policyBillingTypeField = value;
                this.RaisePropertyChanged("PolicyBillingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PolicyDelinquencyCount {
            get {
                return this.policyDelinquencyCountField;
            }
            set {
                this.policyDelinquencyCountField = value;
                this.RaisePropertyChanged("PolicyDelinquencyCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gaic.com/bc/AgentPortalBillingServices")]
    public partial class AccountNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", ConfigurationName="BcPortalService.AgentPortalBillingServices")]
    public interface AgentPortalBillingServices {
        
        // CODEGEN: Generating message contract since the wrapper name (ListPolicyKeyList) of message PolicyListBillingPoliciesRequest does not match the default value (PolicyListBillingPolicies)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesResponse PolicyListBillingPolicies(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesResponse> PolicyListBillingPoliciesAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (PolicyKeyList) of message PolicyListBillingStatusInquiryRequest does not match the default value (PolicyListBillingStatusInquiry)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryResponse PolicyListBillingStatusInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryResponse> PolicyListBillingStatusInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AllPolicyKeyList) of message PolicyListAllBillingStatusInquiryRequest does not match the default value (PolicyListAllBillingStatusInquiry)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryResponse PolicyListAllBillingStatusInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryResponse> PolicyListAllBillingStatusInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AccountPolicyKeyList) of message PolicyListBillingAccountsRequest does not match the default value (PolicyListBillingAccounts)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsResponse PolicyListBillingAccounts(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsResponse> PolicyListBillingAccountsAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyNotFoundException), Action="", Name="PolicyNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryResponse PolicyBillingInfoInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryResponse> PolicyBillingInfoInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountNotFoundException), Action="", Name="AccountNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryResponse AccountBillingInfoInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryResponse> AccountBillingInfoInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryRequest request);
        
        // CODEGEN: Generating message contract since the operation getVersion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="tns:getVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BillingTransaction[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Policy[]))]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionResponse getVersion(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tns:getVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionResponse> getVersionAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPolicyKeyList", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListBillingPoliciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public string[] Key;
        
        public PolicyListBillingPoliciesRequest() {
        }
        
        public PolicyListBillingPoliciesRequest(string[] Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PoliciesResponse", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListBillingPoliciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PoliciesResponse")]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Policy[] PoliciesResponse;
        
        public PolicyListBillingPoliciesResponse() {
        }
        
        public PolicyListBillingPoliciesResponse(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Policy[] PoliciesResponse) {
            this.PoliciesResponse = PoliciesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyKeyList", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListBillingStatusInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public string[] Key;
        
        public PolicyListBillingStatusInquiryRequest() {
        }
        
        public PolicyListBillingStatusInquiryRequest(string[] Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyStatusList", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListBillingStatusInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PolicyStatusResponse", IsNullable=true)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyStatusResponse[] PolicyStatusResponse;
        
        public PolicyListBillingStatusInquiryResponse() {
        }
        
        public PolicyListBillingStatusInquiryResponse(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyStatusResponse[] PolicyStatusResponse) {
            this.PolicyStatusResponse = PolicyStatusResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllPolicyKeyList", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListAllBillingStatusInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public string[] Key;
        
        public PolicyListAllBillingStatusInquiryRequest() {
        }
        
        public PolicyListAllBillingStatusInquiryRequest(string[] Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyStatusList", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListAllBillingStatusInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PolicyStatusResponse", IsNullable=true)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyStatusResponse[] PolicyStatusResponse;
        
        public PolicyListAllBillingStatusInquiryResponse() {
        }
        
        public PolicyListAllBillingStatusInquiryResponse(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyStatusResponse[] PolicyStatusResponse) {
            this.PolicyStatusResponse = PolicyStatusResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountPolicyKeyList", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListBillingAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public string[] Key;
        
        public PolicyListBillingAccountsRequest() {
        }
        
        public PolicyListBillingAccountsRequest(string[] Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyAccountsResponse", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyListBillingAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PolicyAccountsResponse")]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Account[] PolicyAccountsResponse;
        
        public PolicyListBillingAccountsResponse() {
        }
        
        public PolicyListBillingAccountsResponse(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Account[] PolicyAccountsResponse) {
            this.PolicyAccountsResponse = PolicyAccountsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyKey", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyBillingInfoInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        public string PolicyKey;
        
        public PolicyBillingInfoInquiryRequest() {
        }
        
        public PolicyBillingInfoInquiryRequest(string PolicyKey) {
            this.PolicyKey = PolicyKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PolicyInfo", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class PolicyBillingInfoInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        public string PolicyNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=1)]
        public string PolicySymbol;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=2)]
        public string PolicyModule;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=4)]
        public string AccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PolicyEffDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PolicyExpiryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=7)]
        public string PolicyBillingStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyTotalPremium;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyBalance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyAmtPastDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyAmtDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyAmtCurrentDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyTotalNetPremium;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyNetBalance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyNetAmtPastDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyNetAmtDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PolicyNetAmtCurrentDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyPaymentPlan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=20)]
        public string PolicyBusinessUnit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=21)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyProducerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=22)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> PolicyNextDueDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=23)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicySendStatementBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=24)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PolicyBillingRepEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=25)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingTransaction[] BillingTransactions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=26)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ScheduledPayment", IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Payment[] ScheduledPayments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=27)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PolicyBillingDocument", IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingDocument[] BillingDocuments;
        
        public PolicyBillingInfoInquiryResponse() {
        }
        
        public PolicyBillingInfoInquiryResponse(
                    string PolicyNumber, 
                    string PolicySymbol, 
                    string PolicyModule, 
                    string PolicyVersion, 
                    string AccountNumber, 
                    System.DateTime PolicyEffDate, 
                    System.DateTime PolicyExpiryDate, 
                    string PolicyBillingStatus, 
                    System.Nullable<decimal> PolicyTotalPremium, 
                    System.Nullable<decimal> PolicyBalance, 
                    System.Nullable<decimal> PolicyAmtPastDue, 
                    System.Nullable<decimal> PolicyAmtDue, 
                    System.Nullable<decimal> PolicyAmtCurrentDue, 
                    System.Nullable<decimal> PolicyTotalNetPremium, 
                    System.Nullable<decimal> PolicyNetBalance, 
                    System.Nullable<decimal> PolicyNetAmtPastDue, 
                    System.Nullable<decimal> PolicyNetAmtDue, 
                    System.Nullable<decimal> PolicyNetAmtCurrentDue, 
                    string PolicyStatus, 
                    string PolicyPaymentPlan, 
                    string PolicyBusinessUnit, 
                    string PolicyProducerCode, 
                    System.Nullable<System.DateTime> PolicyNextDueDate, 
                    string PolicySendStatementBy, 
                    string PolicyBillingRepEmail, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingTransaction[] BillingTransactions, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Payment[] ScheduledPayments, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingDocument[] BillingDocuments) {
            this.PolicyNumber = PolicyNumber;
            this.PolicySymbol = PolicySymbol;
            this.PolicyModule = PolicyModule;
            this.PolicyVersion = PolicyVersion;
            this.AccountNumber = AccountNumber;
            this.PolicyEffDate = PolicyEffDate;
            this.PolicyExpiryDate = PolicyExpiryDate;
            this.PolicyBillingStatus = PolicyBillingStatus;
            this.PolicyTotalPremium = PolicyTotalPremium;
            this.PolicyBalance = PolicyBalance;
            this.PolicyAmtPastDue = PolicyAmtPastDue;
            this.PolicyAmtDue = PolicyAmtDue;
            this.PolicyAmtCurrentDue = PolicyAmtCurrentDue;
            this.PolicyTotalNetPremium = PolicyTotalNetPremium;
            this.PolicyNetBalance = PolicyNetBalance;
            this.PolicyNetAmtPastDue = PolicyNetAmtPastDue;
            this.PolicyNetAmtDue = PolicyNetAmtDue;
            this.PolicyNetAmtCurrentDue = PolicyNetAmtCurrentDue;
            this.PolicyStatus = PolicyStatus;
            this.PolicyPaymentPlan = PolicyPaymentPlan;
            this.PolicyBusinessUnit = PolicyBusinessUnit;
            this.PolicyProducerCode = PolicyProducerCode;
            this.PolicyNextDueDate = PolicyNextDueDate;
            this.PolicySendStatementBy = PolicySendStatementBy;
            this.PolicyBillingRepEmail = PolicyBillingRepEmail;
            this.BillingTransactions = BillingTransactions;
            this.ScheduledPayments = ScheduledPayments;
            this.BillingDocuments = BillingDocuments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountInquiry", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class AccountBillingInfoInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        public string AccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=1)]
        public int NumberOfMonthsForHistory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=2)]
        public bool OnlyIncludeInForce;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=3)]
        public bool InlcudeTransactions;
        
        public AccountBillingInfoInquiryRequest() {
        }
        
        public AccountBillingInfoInquiryRequest(string AccountNumber, int NumberOfMonthsForHistory, bool OnlyIncludeInForce, bool InlcudeTransactions) {
            this.AccountNumber = AccountNumber;
            this.NumberOfMonthsForHistory = NumberOfMonthsForHistory;
            this.OnlyIncludeInForce = OnlyIncludeInForce;
            this.InlcudeTransactions = InlcudeTransactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountInfo", WrapperNamespace="http://gaic.com/bc/AgentPortalBillingServices", IsWrapped=true)]
    public partial class AccountBillingInfoInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        public string AccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=1)]
        public string AccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=2)]
        public string AccountStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=3)]
        public string SendInvoicesBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=4)]
        public decimal AccountBalance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=5)]
        public decimal AmountDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LastPaymentAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> LastPaymentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> LastInvoiceDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> InvoiceDueDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=10)]
        public string PaymentPlan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=11)]
        public string SendProducerOutputBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=12)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingTransaction[] BillingTransactions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=13)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ScheduledPayment", IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Payment[] ScheduledPayments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=14)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountBillingDocument", IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingDocument[] BillingDocuments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=15)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Policy[] Policies;
        
        public AccountBillingInfoInquiryResponse() {
        }
        
        public AccountBillingInfoInquiryResponse(
                    string AccountNumber, 
                    string AccountName, 
                    string AccountStatus, 
                    string SendInvoicesBy, 
                    decimal AccountBalance, 
                    decimal AmountDue, 
                    System.Nullable<decimal> LastPaymentAmount, 
                    System.Nullable<System.DateTime> LastPaymentDate, 
                    System.Nullable<System.DateTime> LastInvoiceDate, 
                    System.Nullable<System.DateTime> InvoiceDueDate, 
                    string PaymentPlan, 
                    string SendProducerOutputBy, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingTransaction[] BillingTransactions, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Payment[] ScheduledPayments, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingDocument[] BillingDocuments, 
                    com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Policy[] Policies) {
            this.AccountNumber = AccountNumber;
            this.AccountName = AccountName;
            this.AccountStatus = AccountStatus;
            this.SendInvoicesBy = SendInvoicesBy;
            this.AccountBalance = AccountBalance;
            this.AmountDue = AmountDue;
            this.LastPaymentAmount = LastPaymentAmount;
            this.LastPaymentDate = LastPaymentDate;
            this.LastInvoiceDate = LastInvoiceDate;
            this.InvoiceDueDate = InvoiceDueDate;
            this.PaymentPlan = PaymentPlan;
            this.SendProducerOutputBy = SendProducerOutputBy;
            this.BillingTransactions = BillingTransactions;
            this.ScheduledPayments = ScheduledPayments;
            this.BillingDocuments = BillingDocuments;
            this.Policies = Policies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VersionRequest {
        
        public VersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gaic.com/bc/AgentPortalBillingServices", Order=0)]
        public string version;
        
        public VersionResponse() {
        }
        
        public VersionResponse(string version) {
            this.version = version;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentPortalBillingServicesChannel : com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentPortalBillingServicesClient : System.ServiceModel.ClientBase<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices>, com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices {
        
        public AgentPortalBillingServicesClient() {
        }
        
        public AgentPortalBillingServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentPortalBillingServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentPortalBillingServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentPortalBillingServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListBillingPolicies(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest request) {
            return base.Channel.PolicyListBillingPolicies(request);
        }
        
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Policy[] PolicyListBillingPolicies(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest();
            inValue.Key = Key;
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListBillingPolicies(inValue);
            return retVal.PoliciesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesResponse> com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListBillingPoliciesAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest request) {
            return base.Channel.PolicyListBillingPoliciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesResponse> PolicyListBillingPoliciesAsync(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingPoliciesRequest();
            inValue.Key = Key;
            return ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListBillingPoliciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListBillingStatusInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest request) {
            return base.Channel.PolicyListBillingStatusInquiry(request);
        }
        
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyStatusResponse[] PolicyListBillingStatusInquiry(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest();
            inValue.Key = Key;
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListBillingStatusInquiry(inValue);
            return retVal.PolicyStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryResponse> com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListBillingStatusInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest request) {
            return base.Channel.PolicyListBillingStatusInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryResponse> PolicyListBillingStatusInquiryAsync(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingStatusInquiryRequest();
            inValue.Key = Key;
            return ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListBillingStatusInquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListAllBillingStatusInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest request) {
            return base.Channel.PolicyListAllBillingStatusInquiry(request);
        }
        
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyStatusResponse[] PolicyListAllBillingStatusInquiry(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest();
            inValue.Key = Key;
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListAllBillingStatusInquiry(inValue);
            return retVal.PolicyStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryResponse> com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListAllBillingStatusInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest request) {
            return base.Channel.PolicyListAllBillingStatusInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryResponse> PolicyListAllBillingStatusInquiryAsync(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListAllBillingStatusInquiryRequest();
            inValue.Key = Key;
            return ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListAllBillingStatusInquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListBillingAccounts(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest request) {
            return base.Channel.PolicyListBillingAccounts(request);
        }
        
        public com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Account[] PolicyListBillingAccounts(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest();
            inValue.Key = Key;
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListBillingAccounts(inValue);
            return retVal.PolicyAccountsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsResponse> com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyListBillingAccountsAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest request) {
            return base.Channel.PolicyListBillingAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsResponse> PolicyListBillingAccountsAsync(string[] Key) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyListBillingAccountsRequest();
            inValue.Key = Key;
            return ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyListBillingAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.PolicyBillingInfoInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryRequest request) {
            return base.Channel.PolicyBillingInfoInquiry(request);
        }
        
        public string PolicyBillingInfoInquiry(
                    string PolicyKey, 
                    out string PolicySymbol, 
                    out string PolicyModule, 
                    out string PolicyVersion, 
                    out string AccountNumber, 
                    out System.DateTime PolicyEffDate, 
                    out System.DateTime PolicyExpiryDate, 
                    out string PolicyBillingStatus, 
                    out System.Nullable<decimal> PolicyTotalPremium, 
                    out System.Nullable<decimal> PolicyBalance, 
                    out System.Nullable<decimal> PolicyAmtPastDue, 
                    out System.Nullable<decimal> PolicyAmtDue, 
                    out System.Nullable<decimal> PolicyAmtCurrentDue, 
                    out System.Nullable<decimal> PolicyTotalNetPremium, 
                    out System.Nullable<decimal> PolicyNetBalance, 
                    out System.Nullable<decimal> PolicyNetAmtPastDue, 
                    out System.Nullable<decimal> PolicyNetAmtDue, 
                    out System.Nullable<decimal> PolicyNetAmtCurrentDue, 
                    out string PolicyStatus, 
                    out string PolicyPaymentPlan, 
                    out string PolicyBusinessUnit, 
                    out string PolicyProducerCode, 
                    out System.Nullable<System.DateTime> PolicyNextDueDate, 
                    out string PolicySendStatementBy, 
                    out string PolicyBillingRepEmail, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingTransaction[] BillingTransactions, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Payment[] ScheduledPayments, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingDocument[] BillingDocuments) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryRequest();
            inValue.PolicyKey = PolicyKey;
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).PolicyBillingInfoInquiry(inValue);
            PolicySymbol = retVal.PolicySymbol;
            PolicyModule = retVal.PolicyModule;
            PolicyVersion = retVal.PolicyVersion;
            AccountNumber = retVal.AccountNumber;
            PolicyEffDate = retVal.PolicyEffDate;
            PolicyExpiryDate = retVal.PolicyExpiryDate;
            PolicyBillingStatus = retVal.PolicyBillingStatus;
            PolicyTotalPremium = retVal.PolicyTotalPremium;
            PolicyBalance = retVal.PolicyBalance;
            PolicyAmtPastDue = retVal.PolicyAmtPastDue;
            PolicyAmtDue = retVal.PolicyAmtDue;
            PolicyAmtCurrentDue = retVal.PolicyAmtCurrentDue;
            PolicyTotalNetPremium = retVal.PolicyTotalNetPremium;
            PolicyNetBalance = retVal.PolicyNetBalance;
            PolicyNetAmtPastDue = retVal.PolicyNetAmtPastDue;
            PolicyNetAmtDue = retVal.PolicyNetAmtDue;
            PolicyNetAmtCurrentDue = retVal.PolicyNetAmtCurrentDue;
            PolicyStatus = retVal.PolicyStatus;
            PolicyPaymentPlan = retVal.PolicyPaymentPlan;
            PolicyBusinessUnit = retVal.PolicyBusinessUnit;
            PolicyProducerCode = retVal.PolicyProducerCode;
            PolicyNextDueDate = retVal.PolicyNextDueDate;
            PolicySendStatementBy = retVal.PolicySendStatementBy;
            PolicyBillingRepEmail = retVal.PolicyBillingRepEmail;
            BillingTransactions = retVal.BillingTransactions;
            ScheduledPayments = retVal.ScheduledPayments;
            BillingDocuments = retVal.BillingDocuments;
            return retVal.PolicyNumber;
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryResponse> PolicyBillingInfoInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.PolicyBillingInfoInquiryRequest request) {
            return base.Channel.PolicyBillingInfoInquiryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.AccountBillingInfoInquiry(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryRequest request) {
            return base.Channel.AccountBillingInfoInquiry(request);
        }
        
        public string AccountBillingInfoInquiry(
                    ref string AccountNumber, 
                    int NumberOfMonthsForHistory, 
                    bool OnlyIncludeInForce, 
                    bool InlcudeTransactions, 
                    out string AccountStatus, 
                    out string SendInvoicesBy, 
                    out decimal AccountBalance, 
                    out decimal AmountDue, 
                    out System.Nullable<decimal> LastPaymentAmount, 
                    out System.Nullable<System.DateTime> LastPaymentDate, 
                    out System.Nullable<System.DateTime> LastInvoiceDate, 
                    out System.Nullable<System.DateTime> InvoiceDueDate, 
                    out string PaymentPlan, 
                    out string SendProducerOutputBy, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingTransaction[] BillingTransactions, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Payment[] ScheduledPayments, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.BillingDocument[] BillingDocuments, 
                    out com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.Policy[] Policies) {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryRequest();
            inValue.AccountNumber = AccountNumber;
            inValue.NumberOfMonthsForHistory = NumberOfMonthsForHistory;
            inValue.OnlyIncludeInForce = OnlyIncludeInForce;
            inValue.InlcudeTransactions = InlcudeTransactions;
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).AccountBillingInfoInquiry(inValue);
            AccountNumber = retVal.AccountNumber;
            AccountStatus = retVal.AccountStatus;
            SendInvoicesBy = retVal.SendInvoicesBy;
            AccountBalance = retVal.AccountBalance;
            AmountDue = retVal.AmountDue;
            LastPaymentAmount = retVal.LastPaymentAmount;
            LastPaymentDate = retVal.LastPaymentDate;
            LastInvoiceDate = retVal.LastInvoiceDate;
            InvoiceDueDate = retVal.InvoiceDueDate;
            PaymentPlan = retVal.PaymentPlan;
            SendProducerOutputBy = retVal.SendProducerOutputBy;
            BillingTransactions = retVal.BillingTransactions;
            ScheduledPayments = retVal.ScheduledPayments;
            BillingDocuments = retVal.BillingDocuments;
            Policies = retVal.Policies;
            return retVal.AccountName;
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryResponse> AccountBillingInfoInquiryAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AccountBillingInfoInquiryRequest request) {
            return base.Channel.AccountBillingInfoInquiryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionResponse com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.getVersion(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest();
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionResponse retVal = ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).getVersion(inValue);
            return retVal.version;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionResponse> com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices.getVersionAsync(com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionResponse> getVersionAsync() {
            com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest inValue = new com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.VersionRequest();
            return ((com.gaic.insuredPortal.Provider.WcfServices.BcPortalService.AgentPortalBillingServices)(this)).getVersionAsync(inValue);
        }
    }
}
